//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusInfoTB
    {
        public int ID { get; set; }
        public string BusName { get; set; }
        public string BusNumber { get; set; }
        public int TotalSits { get; set; }
        public string BusType { get; set; }
    }
}
