//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteDetailsTB
    {
        public int ID { get; set; }
        public Nullable<int> RouteID { get; set; }
        public Nullable<int> NextCounter { get; set; }
        public string NCDistanceTime { get; set; }
        public Nullable<decimal> SerielNo { get; set; }
    
        public virtual RouteInfoTB RouteInfoTB { get; set; }
    }
}
