//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteInfoTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RouteInfoTB()
        {
            this.RouteDetailsTBs = new HashSet<RouteDetailsTB>();
            this.TripInfoTBs = new HashSet<TripInfoTB>();
        }
    
        public int RouteID { get; set; }
        public string Name { get; set; }
        public Nullable<int> BegCounter { get; set; }
        public Nullable<int> EndCounter { get; set; }
        public Nullable<int> CounterID { get; set; }
    
        public virtual CounterInfoTB CounterInfoTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteDetailsTB> RouteDetailsTBs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripInfoTB> TripInfoTBs { get; set; }
    }
}
