//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSalesInfoTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketSalesInfoTB()
        {
            this.TicketSelesDeteils = new HashSet<TicketSelesDeteil>();
        }
    
        public int ID { get; set; }
        public string Mobile { get; set; }
        public string CustomerName { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public string Address { get; set; }
        public Nullable<int> Boarding { get; set; }
        public Nullable<int> Droping { get; set; }
        public Nullable<decimal> TotalFare { get; set; }
        public Nullable<int> TotalSeat { get; set; }
        public Nullable<System.DateTime> BoardingTime { get; set; }
        public Nullable<int> TripID { get; set; }
        public Nullable<int> SaleBy { get; set; }
        public Nullable<bool> IsSalle { get; set; }
        public Nullable<System.DateTime> TicketSaleTime { get; set; }
    
        public virtual TripInfoTB TripInfoTB { get; set; }
        public virtual UserInfoTB UserInfoTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketSelesDeteil> TicketSelesDeteils { get; set; }
    }
}
