//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketSelesDeteil
    {
        public int ID { get; set; }
        public Nullable<int> TicketSalesInfoID { get; set; }
        public string BusSitNumber { get; set; }
        public Nullable<decimal> SitsPrice { get; set; }
    
        public virtual TicketSalesInfoTB TicketSalesInfoTB { get; set; }
    }
}
