//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusTicket
{
    using System;
    using System.Collections.Generic;
    
    public partial class TripInfoTB
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> PerSitPrice { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<int> BusID { get; set; }
        public Nullable<int> CounterID { get; set; }
        public Nullable<int> RouteID { get; set; }
        public Nullable<int> DriverID { get; set; }
        public Nullable<int> SuperVisorID { get; set; }
    
        public virtual BusInfoTB BusInfoTB { get; set; }
        public virtual DriverInfoTB DriverInfoTB { get; set; }
        public virtual RouteInfoTB RouteInfoTB { get; set; }
        public virtual SuperViseorInfoTB SuperViseorInfoTB { get; set; }
    }
}
